const grid=document.querySelector('#skill-grid'),search=document.querySelector('#search'),detail=document.querySelector('#detail'),detailContent=document.querySelector('#detail-content'),scrim=document.querySelector('#drawer-scrim'),player=document.querySelector('#player-modal'),video=document.querySelector('#demo-video'),playerMeta=document.querySelector('#player-meta');
let catalog=null,category='all',statusMode='all';
const labels={pass:'PASS',conditional:'CONDITIONAL',prototype:'PROTOTYPE'};
const categoryLabels={gate:'Content Gate',core:'Core Capability',editing:'Base Editing',visual:'Visual / Layout',evidence:'Evidence / B-roll',text:'Subtitle / Typography',audio:'Audio',composite:'Composite Director',orchestrator:'Orchestrator'};
function esc(v=''){return String(v).replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]));}
function preview(m){if(m.public_demo&&window.SKILL_MEDIA?.[m.media_key])return `<video muted preload="metadata" src="${window.SKILL_MEDIA[m.media_key]}"></video><span class="preview-chip">VALIDATED DEMO</span><button class="play-demo" data-play="${m.id}">▶ 播放样片</button>`;const mark=m.level==='core_capability'?'CORE':m.level==='orchestrator'?'ORCH':m.level==='system_gate'?'GATE':m.level==='composite_skill'?'DIR':'SKILL';return `<div class="preview-placeholder">${mark}</div><span class="preview-chip">${esc(categoryLabels[m.category]||m.category)}</span>`;}
function card(m){const st=m.validation_status||'prototype';const demo=m.demo_status?`<span>${esc(m.demo_status)}</span>`:'';return `<article class="skill-card"><div class="card-preview">${preview(m)}</div><div class="card-body"><div class="card-top"><span class="skill-id">${esc(m.id)} · v${esc(m.version)}</span><span class="status-badge ${st}">${labels[st]||st}</span></div><h3>${esc(m.name_zh)}</h3><div class="english">${esc(m.name_en)}</div><p class="summary">${esc(m.summary)}</p><div class="card-foot"><div class="meta-chips"><span>${esc(categoryLabels[m.category]||m.category)}</span>${demo}</div><button class="details-btn" data-detail="${m.id}">查看 →</button></div></div></article>`;}
function matches(m){const q=search.value.trim().toLowerCase();const catOK=category==='all'||category.split(',').includes(m.category);const statusOK=statusMode==='all'||(statusMode==='demo'?m.demo_ready:m.validation_status===statusMode);return catOK&&statusOK&&(!q||`${m.id} ${m.name_zh} ${m.name_en} ${m.summary}`.toLowerCase().includes(q));}
function render(){const items=catalog.modules.filter(matches);grid.innerHTML=items.length?items.map(card).join(''):'<div class="empty">没有符合筛选条件的能力。</div>';document.querySelector('#result-count').textContent=items.length;document.querySelectorAll('[data-detail]').forEach(b=>b.onclick=()=>openDetail(b.dataset.detail));document.querySelectorAll('[data-play]').forEach(b=>b.onclick=e=>{e.stopPropagation();openPlayer(b.dataset.play)});}
function openDetail(id){const m=catalog.modules.find(x=>x.id===id);if(!m)return;const deps=(m.depends_on||[]).length?m.depends_on:['无'];const recipes=m.recipes||[m.default_recipe].filter(Boolean);const st=m.validation_status||'prototype';detailContent.innerHTML=`<div class="detail-kicker">${esc(m.id)} · v${esc(m.version)}</div><h2>${esc(m.name_zh)}</h2><div class="detail-en">${esc(m.name_en)}</div><span class="status-badge ${st}">${esc(m.validation_label||labels[st]||st)}</span>${m.public_demo?`<button class="detail-play" data-play-detail="${m.id}">▶ 播放验证样片</button>`:''}<div class="detail-row"><label>定位</label><p>${esc(m.summary)}</p></div><div class="detail-row"><label>联合测试证据</label><p>${esc(m.validation_evidence||'暂无')}</p></div><div class="detail-row"><label>系统层级</label><div class="detail-tags"><span>${esc(m.level)}</span><span>${esc(categoryLabels[m.category]||m.category)}</span></div></div><div class="detail-row"><label>生命周期状态</label><p>${esc(m.lifecycle_status||'—')}</p></div><div class="detail-row"><label>依赖</label><div class="detail-tags">${deps.map(x=>`<span>${esc(x)}</span>`).join('')}</div></div><div class="detail-row"><label>Recipes</label><div class="detail-tags">${recipes.length?recipes.map(x=>`<span>${esc(x)}</span>`).join(''):'<span>暂无固定 Recipe</span>'}</div></div><div class="detail-row"><label>样片</label><p>${esc(m.demo_status||(m.demo_ready?'ready':'尚未标准化'))}</p></div>`;detail.classList.add('open');scrim.classList.add('open');const p=detailContent.querySelector('[data-play-detail]');if(p)p.onclick=()=>openPlayer(id);}
function openPlayer(id){const m=catalog.modules.find(x=>x.id===id),src=window.SKILL_MEDIA?.[id];if(!src)return;video.src=src;playerMeta.textContent=`${m.id} · ${m.name_zh} / ${m.name_en} · v${m.version}`;player.classList.add('open');video.play().catch(()=>{});}
function closeDetail(){detail.classList.remove('open');scrim.classList.remove('open')}function closePlayer(){video.pause();video.removeAttribute('src');video.load();player.classList.remove('open')}
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('is-active'));b.classList.add('is-active');category=b.dataset.category;render()});document.querySelectorAll('.status-filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.status-filter').forEach(x=>x.classList.remove('is-active'));b.classList.add('is-active');statusMode=b.dataset.status;render()});search.addEventListener('input',render);document.querySelector('#detail-close').onclick=closeDetail;scrim.onclick=closeDetail;document.querySelector('#player-close').onclick=closePlayer;player.addEventListener('click',e=>{if(e.target===player)closePlayer()});
fetch('data/skills/catalog.json').then(r=>r.json()).then(data=>{catalog=data;const c=data.counts;document.querySelector('#metric-total').textContent=c.total_modules;document.querySelector('#metric-atomic').textContent=c.atomic_skills;document.querySelector('#metric-pass').textContent=c.pass;document.querySelector('#metric-demo').textContent=c.demo_ready;document.querySelector('#count-all').textContent=c.total_modules;render()}).catch(err=>{grid.innerHTML=`<div class="empty">能力目录加载失败：${esc(err.message)}</div>`});
