const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const STEPS={clone:[['上传参考','提取结构'],['AI 分析','生成 DNA'],['替换主体','人物或产品'],['生成视频','输出新版本']],avatar:[['数字分身','照片或视频'],['声音克隆','录音或提取'],['输入文案','新口播内容'],['生成口播','合成视频']]};
const state={route:'home',cloneStep:0,avatarStep:0,clone:{reference:null,analyzed:false,type:'person',subjects:[],generated:false},avatar:{media:null,kind:'photo',voice:null,source:'audio',script:'',generated:false},projects:JSON.parse(localStorage.getItem('vc_v2_projects')||'null')||[{title:'智能手表复刻宣传片',mode:'clone',time:'今天 06:18',img:'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=220&q=70'},{title:'我的 AI 工具口播',mode:'avatar',time:'昨天 21:28',img:'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=220&q=70'},{title:'产品介绍短视频',mode:'clone',time:'08/04 18:30',img:'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=220&q=70'}]};
const meta={home:['VideoClone OS','双核心公开测试版 · 文件仅在浏览器本地预览'],projects:['我的项目','复刻项目和口播项目分开管理'],assets:['素材库','人物、产品、声音与品牌资产'],templates:['模板库','两种功能使用独立模板体系'],profile:['我的','账户、额度和隐私设置'],clone:['AI 视频复刻','参考视频与替换主体完全分开'],avatar:['AI 口播生成','形象、声音和文案分别创建']};
function save(){localStorage.setItem('vc_v2_projects',JSON.stringify(state.projects));$('#quota').textContent=Math.max(0,324-state.projects.length*2)+' 分钟'}
function toast(t,x,g=false){$('#toastTitle').textContent=t;$('#toastText').textContent=x;$('#toast').className='toast show'+(g?' green':'');clearTimeout(window._tt);window._tt=setTimeout(()=>$('#toast').className='toast',3000)}
function closeDrawer(){$('#drawer').classList.remove('show');$('#shade').classList.remove('show')}function openDrawer(){$('#drawer').classList.add('show');$('#shade').classList.add('show')}
function go(route){state.route=route;$$('.page').forEach(p=>p.classList.remove('active'));$('#'+route).classList.add('active');$('#title').textContent=meta[route][0];$('#sub').textContent=meta[route][1];$$('[data-go]').forEach(b=>b.classList.toggle('on',b.dataset.go===route));closeDrawer();scrollTo({top:0,behavior:'smooth'});if(route==='projects')renderProjects()}
function start(flow){go(flow);renderSteps(flow);renderStage(flow)}
function allowed(flow){if(flow==='clone'){if(!state.clone.reference)return 0;if(!state.clone.analyzed)return 1;if(!state.clone.subjects.length)return 2;return 3}if(!state.avatar.media)return 0;if(!state.avatar.voice)return 1;if(state.avatar.script.trim().length<8)return 2;return 3}
function renderSteps(flow){const n=state[flow+'Step'];$('#'+flow+'Steps').innerHTML=STEPS[flow].map((s,i)=>`<button class="${i===n?'on':i<n?'done':''}" data-step="${i}"><b><i>${i+1}</i>${s[0]}</b><span>${s[1]}</span></button>`).join('');$$('[data-step]',$('#'+flow+'Steps')).forEach(b=>b.onclick=()=>{const i=+b.dataset.step;if(i<=allowed(flow)){state[flow+'Step']=i;renderSteps(flow);renderStage(flow)}else toast('请先完成当前步骤','两条流程会按顺序推进。',flow==='avatar')})}
function renderStage(flow){const n=state[flow+'Step'];$$(`[data-${flow}]`).forEach(p=>p.classList.toggle('active',+p.dataset[flow]===n));const prev=$('#'+flow+'Prev'),next=$('#'+flow+'Next');prev.style.visibility=n?'visible':'hidden';next.textContent=n<3?'下一步':flow==='clone'?'开始生成复刻视频':'开始生成口播视频';next.classList.toggle('hidden',state[flow].generated);if(flow==='avatar'&&n===3)updateChecks()}
function error(flow){const n=state[flow+'Step'];if(flow==='clone'){if(n===0&&!state.clone.reference)return'请上传参考视频';if(n===1&&!state.clone.analyzed)return'请完成参考视频分析';if(n===2&&!state.clone.subjects.length)return'请上传替换主体';if(n===3&&$('#cloneBrief').value.trim().length<8)return'请填写新视频内容'}else{if(n===0&&!state.avatar.media)return'请上传照片或自拍视频';if(n===1&&!state.avatar.voice)return'请上传录音或说话视频';if(n===2&&state.avatar.script.trim().length<8)return'请输入至少 8 个字的口播文案'}return''}
function next(flow){const e=error(flow);if(e)return toast('当前步骤未完成',e,flow==='avatar');if(state[flow+'Step']<3){state[flow+'Step']++;renderSteps(flow);renderStage(flow);scrollTo({top:0,behavior:'smooth'})}else generate(flow)}function prev(flow){state[flow+'Step']=Math.max(0,state[flow+'Step']-1);renderSteps(flow);renderStage(flow)}
function url(f){try{return URL.createObjectURL(f)}catch{return''}}function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function preview(zone,copy,file){$('video,img',zone)?.remove();const m=document.createElement(file.type.startsWith('video/')?'video':'img');m.src=url(file);if(m.tagName==='VIDEO'){m.muted=true;m.controls=true;m.playsInline=true}zone.prepend(m);copy.innerHTML=`<i class="ph ph-check-circle"></i><b>${esc(file.name)}</b><span>已在当前浏览器加载</span>`}
function generate(flow){const pre=flow==='clone'?'clone':'avatar';$('#'+pre+'Idle').classList.add('hidden');$('#'+pre+'Generating').classList.remove('hidden');$('#'+pre+'Actions').classList.add('hidden');const ring=$('#'+pre+'Ring'),text=$('#'+pre+'Percent'),caption=$('#'+pre+'Caption');let p=0;const timer=setInterval(()=>{p=Math.min(100,p+13);ring.style.setProperty('--p',p*3.6+'deg');text.textContent=p+'%';caption.textContent=p<30?'正在分析素材…':p<60?'正在生成画面与声音…':p<100?'正在合成与质检…':'生成完成';if(p===100){clearInterval(timer);setTimeout(()=>{$('#'+pre+'Generating').classList.add('hidden');$('#'+pre+'Result').classList.remove('hidden');state[flow].generated=true;renderStage(flow);state.projects.unshift({title:flow==='clone'?'新建视频复刻项目':'新建 AI 口播项目',mode:flow,time:'刚刚',img:flow==='clone'?'https://images.unsplash.com/photo-1536240478700-b869070f9279?auto=format&fit=crop&w=220&q=70':'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=220&q=70'});save();renderRecent();toast(flow==='clone'?'视频复刻流程完成':'AI 口播流程完成','这是模拟成片，真实 API 尚未接入。',flow==='avatar')},350)}},550)}
function updateChecks(){const a=!!state.avatar.media,v=!!state.avatar.voice,s=state.avatar.script.trim().length>=8;$('#mediaState').textContent=a?'已完成':'未完成';$('#voiceState').textContent=v?'已完成':'未完成';$('#scriptState').textContent=s?'已完成':'未完成'}
function renderRecent(){$('#recent').innerHTML=state.projects.slice(0,3).map(p=>`<article><img src="${p.img}"><div><b>${esc(p.title)}</b><span>${p.time} · ${p.mode==='clone'?'视频复刻':'AI 口播'} · 已完成</span></div></article>`).join('')}
function renderProjects(){$('#projectList').innerHTML=state.projects.map(p=>`<article><img src="${p.img}"><div><b>${esc(p.title)}</b><span>${p.time} · 模拟成片已保存</span></div><em>${p.mode==='clone'?'视频复刻':'AI 口播'}</em></article>`).join('')}
$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$$('[data-flow]').forEach(b=>b.onclick=()=>start(b.dataset.flow));$('#menu').onclick=openDrawer;$('#close').onclick=closeDrawer;$('#shade').onclick=closeDrawer;$('#clonePrev').onclick=()=>prev('clone');$('#cloneNext').onclick=()=>next('clone');$('#avatarPrev').onclick=()=>prev('avatar');$('#avatarNext').onclick=()=>next('avatar');
$('#refInput').onchange=e=>{const f=e.target.files[0];if(!f)return;state.clone.reference=f;state.clone.analyzed=false;preview($('#refZone'),$('#refCopy'),f);renderSteps('clone');toast('参考视频已选择','下一步会单独分析视频结构。')};
$('#analyze').onclick=()=>{if(!state.clone.reference)return toast('缺少参考视频','请返回第一步上传参考视频。');$('#analyze').disabled=true;$('#analyze').textContent='正在分析…';setTimeout(()=>{state.clone.analyzed=true;$('#analysis').innerHTML='<div><i class="ph ph-film-strip"></i><b>镜头结构</b><span>12 个镜头</span></div><div><i class="ph ph-wave-sine"></i><b>节奏结构</b><span>钩子＋演示＋CTA</span></div><div><i class="ph ph-text-aa"></i><b>字幕文案</b><span>关键词放大</span></div><div><i class="ph ph-palette"></i><b>视觉风格</b><span>明亮蓝紫调</span></div>';$('#analyze').disabled=false;$('#analyze').textContent='重新模拟分析';renderSteps('clone');toast('分析完成','已生成模拟 Video DNA。')},1100)};
$$('button',$('#replaceTabs')).forEach(b=>b.onclick=()=>{$$('button',$('#replaceTabs')).forEach(x=>x.classList.remove('on'));b.classList.add('on');state.clone.type=b.dataset.type;$('#subjectCopy').innerHTML=b.dataset.type==='person'?'<i class="ph ph-user-focus"></i><b>上传人物照片或自拍视频</b><span>可多选，建议主体清晰完整</span>':'<i class="ph ph-package"></i><b>上传产品图片或视频</b><span>建议多角度与干净背景</span>'});
$('#subjectInput').onchange=e=>{state.clone.subjects=[...e.target.files];$('#subjectPreviews').innerHTML=state.clone.subjects.slice(0,4).map(f=>f.type.startsWith('video/')?`<video src="${url(f)}" muted></video>`:`<img src="${url(f)}">`).join('');$('#subjectCopy').innerHTML=`<i class="ph ph-check-circle"></i><b>已选择 ${state.clone.subjects.length} 个主体素材</b><span>${state.clone.type==='person'?'人物替换':'产品替换'}</span>`;renderSteps('clone');toast('替换主体已准备','参考视频和主体素材已经分开。')};
$$('button',$('#avatarTabs')).forEach(b=>b.onclick=()=>{$$('button',$('#avatarTabs')).forEach(x=>x.classList.remove('on'));b.classList.add('on');state.avatar.kind=b.dataset.kind;$('#avatarInput').accept=b.dataset.kind==='photo'?'image/*':'video/*';$('#avatarCopy').innerHTML=b.dataset.kind==='photo'?'<i class="ph ph-identification-card"></i><b>上传一张正面照片</b><span>自然表情、光线均匀</span>':'<i class="ph ph-video-camera"></i><b>上传一段自拍视频</b><span>建议 10–30 秒正面说话</span>'});
$('#avatarInput').onchange=e=>{const f=e.target.files[0];if(!f)return;state.avatar.media=f;preview($('#avatarZone'),$('#avatarCopy'),f);renderSteps('avatar');toast('数字分身素材已选择','下一步可以克隆声音。',true)};
$$('button',$('#voiceOptions')).forEach(b=>b.onclick=()=>{$$('button',$('#voiceOptions')).forEach(x=>x.classList.remove('on'));b.classList.add('on');state.avatar.source=b.dataset.source;$('#voiceInput').accept=b.dataset.source==='audio'?'audio/*':'video/*';$('#voiceCopy').innerHTML=b.dataset.source==='audio'?'<i class="ph ph-microphone"></i><b>点击上传录音文件</b><span>MP3、WAV，建议 30 秒以上</span>':'<i class="ph ph-video-camera"></i><b>上传已有说话视频</b><span>模拟从视频中提取声音</span>'});
$('#voiceInput').onchange=e=>{const f=e.target.files[0];if(!f)return;state.avatar.voice=f;$('#voiceCopy').innerHTML=`<i class="ph ph-check-circle"></i><b>${esc(f.name)}</b><span>${state.avatar.source==='audio'?'录音已加载':'已模拟提取音轨'}</span>`;renderSteps('avatar');toast('声音素材已准备','真实上线后需要声音授权。',true)};
$('#script').oninput=e=>{state.avatar.script=e.target.value;$('#count').textContent=e.target.value.length+' / 2000';renderSteps('avatar')};$$('.chips').forEach(g=>$$('button',g).forEach(b=>b.onclick=()=>{$$('button',g).forEach(x=>x.classList.remove('on'));b.classList.add('on')}));$('#cloneSave').onclick=()=>{toast('项目已保存','记录已保存到当前浏览器。');go('projects')};$('#avatarSave').onclick=()=>{toast('项目已保存','记录已保存到当前浏览器。',true);go('projects')};renderRecent();renderProjects();save();renderSteps('clone');renderSteps('avatar');renderStage('clone');renderStage('avatar');toast('VideoClone OS V2 已升级','视频复刻与 AI 口播已经拆成两个独立功能。',true);
