const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const STEPS={clone:[['上传参考','提取结构'],['AI 分析','生成 DNA'],['替换主体','人物或产品'],['生成视频','输出新版本']],avatar:[['数字分身','照片或视频'],['声音克隆','录音或提取'],['输入文案','新口播内容'],['生成口播','合成视频']]};
const DEFAULT_PROJECTS=[{title:'智能手表复刻宣传片',mode:'clone',time:'今天 06:18',img:'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=220&q=70'},{title:'我的 AI 工具口播',mode:'avatar',time:'昨天 21:28',img:'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=220&q=70'},{title:'产品介绍短视频',mode:'clone',time:'08/04 18:30',img:'https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=220&q=70'}];
const uid=()=>`vc-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,8)}`;
function normalizeProject(p={}){return{id:String(p.id||uid()),title:String(p.title||'未命名项目'),mode:p.mode==='avatar'?'avatar':'clone',time:String(p.time||'刚刚'),img:String(p.img||''),status:String(p.status||'已完成'),brief:String(p.brief||'模拟成片已保存')}}
function loadProjects(){try{const raw=localStorage.getItem('vc_v2_projects');if(!raw)return DEFAULT_PROJECTS.map(normalizeProject);const parsed=JSON.parse(raw);if(!Array.isArray(parsed))throw new Error('project history is not an array');return parsed.map(normalizeProject)}catch(err){try{localStorage.removeItem('vc_v2_projects')}catch{};console.warn('VideoClone history recovered:',err?.message||err);return DEFAULT_PROJECTS.map(normalizeProject)}}
const state={route:'home',cloneStep:0,avatarStep:0,clone:{reference:null,analyzed:false,type:'person',subjects:[],generated:false,pendingProject:null},avatar:{media:null,kind:'photo',voice:null,source:'audio',script:'',generated:false,pendingProject:null},projects:loadProjects(),projectFilter:'all'};
const meta={home:['VideoClone OS','双核心公开测试版 · 文件仅在浏览器本地预览'],projects:['我的项目','查看结果、再次创作或删除历史记录'],assets:['素材库','人物、产品、声音与品牌资产'],templates:['模板库','两种功能使用独立模板体系'],profile:['我的','账户、额度和隐私设置'],clone:['AI 视频复刻','参考视频与替换主体完全分开'],avatar:['AI 口播生成','形象、声音和文案分别创建']};
function injectQACSS(){const style=document.createElement('style');style.textContent=`.project-actions{display:flex;gap:7px;flex-wrap:wrap;justify-content:flex-end}.project-actions button,.result-actions button,.history-filters button{border:0;border-radius:11px;padding:8px 10px;cursor:pointer;background:linear-gradient(145deg,#fbfcff,#e4e9f3);box-shadow:var(--sm);font-size:10px}.project-actions button.primary-mini,.history-filters button.on{color:white;background:linear-gradient(135deg,var(--blue),var(--purple2))}.recent-card{width:100%;border:0;display:flex;align-items:center;gap:12px;padding:12px;border-radius:18px;text-align:left;color:inherit;cursor:pointer;background:linear-gradient(145deg,#fbfcff,#e5eaf4);box-shadow:var(--sm)}.recent-card img{width:62px;height:52px;border-radius:13px;object-fit:cover}.recent-card b{display:block;font-size:13px}.recent-card span{display:block;margin-top:5px;color:var(--muted);font-size:9px}.history-filters{display:flex;gap:8px;margin:0 0 14px;flex-wrap:wrap}.project-modal{position:fixed;inset:0;z-index:90;display:none;place-items:center;padding:20px;background:#10172d99;backdrop-filter:blur(12px)}.project-modal.show{display:grid}.project-dialog{width:min(560px,100%);border-radius:25px;padding:22px;background:linear-gradient(145deg,#fbfcff,#e5eaf4);box-shadow:var(--lg)}.project-dialog header{display:flex;align-items:flex-start;justify-content:space-between;gap:12px}.project-dialog h3{margin:0}.project-dialog p{color:var(--muted);line-height:1.6}.project-preview{min-height:220px;display:grid;place-items:center;border-radius:20px;color:white;font-size:45px;background:radial-gradient(circle at 70% 16%,#6d8bff88,transparent 24%),linear-gradient(160deg,#13234a,#0b1227 66%,#281044);margin:15px 0}.project-preview.avatar{background:radial-gradient(circle at 70% 18%,#4fdcb366,transparent 26%),linear-gradient(160deg,#173c3a,#081d22 70%,#0d2f28)}.result-actions{display:flex;gap:9px;flex-wrap:wrap;margin-top:13px}.notice-dot{position:relative}.notice-dot:after{content:'1';position:absolute;right:-4px;top:-5px;min-width:15px;height:15px;padding:0 3px;display:grid;place-items:center;border-radius:99px;background:#ff5c7b;color:white;font-size:8px}.empty-history{padding:45px;text-align:center;color:var(--muted);border-radius:18px;box-shadow:var(--in)}@media(max-width:780px){.project-actions{grid-column:1/-1;justify-content:flex-start}.project-dialog{padding:17px}.project-preview{min-height:185px}}`;document.head.append(style)}
function save(){try{localStorage.setItem('vc_v2_projects',JSON.stringify(state.projects))}catch(err){console.warn('Unable to save VideoClone history:',err?.message||err);toast('历史保存失败','浏览器存储空间不足，请清理后重试。')}const quota=$('#quota');if(quota)quota.textContent=Math.max(0,324-state.projects.length*2)+' 分钟'}
function toast(t,x,g=false){$('#toastTitle').textContent=t;$('#toastText').textContent=x;$('#toast').className='toast show'+(g?' green':'');clearTimeout(window._tt);window._tt=setTimeout(()=>$('#toast').className='toast',3000)}
function closeDrawer(){$('#drawer').classList.remove('show');$('#shade').classList.remove('show')}function openDrawer(){$('#drawer').classList.add('show');$('#shade').classList.add('show')}
function go(route){if(!meta[route]||!$('#'+route))return toast('功能不可用',`页面 ${route} 尚未建立。`);state.route=route;$$('.page').forEach(p=>p.classList.remove('active'));$('#'+route).classList.add('active');$('#title').textContent=meta[route][0];$('#sub').textContent=meta[route][1];$$('[data-go]').forEach(b=>b.classList.toggle('on',b.dataset.go===route));closeDrawer();scrollTo({top:0,behavior:'smooth'});if(route==='projects')renderProjects()}
function start(flow,{fresh=false}={}){if(fresh)resetFlow(flow);go(flow);renderSteps(flow);renderStage(flow)}
function allowed(flow){if(flow==='clone'){if(!state.clone.reference)return 0;if(!state.clone.analyzed)return 1;if(!state.clone.subjects.length)return 2;return 3}if(!state.avatar.media)return 0;if(!state.avatar.voice)return 1;if(state.avatar.script.trim().length<8)return 2;return 3}
function renderSteps(flow){const n=state[flow+'Step'];$('#'+flow+'Steps').innerHTML=STEPS[flow].map((s,i)=>`<button class="${i===n?'on':i<n?'done':''}" data-step="${i}" aria-label="第 ${i+1} 步：${s[0]}"><b><i>${i+1}</i>${s[0]}</b><span>${s[1]}</span></button>`).join('');$$('[data-step]',$('#'+flow+'Steps')).forEach(b=>b.onclick=()=>{const i=+b.dataset.step;if(i<=allowed(flow)){state[flow+'Step']=i;renderSteps(flow);renderStage(flow)}else toast('请先完成当前步骤','两条流程会按顺序推进。',flow==='avatar')})}
function renderStage(flow){const n=state[flow+'Step'];$$(`[data-${flow}]`).forEach(p=>p.classList.toggle('active',+p.dataset[flow]===n));const prev=$('#'+flow+'Prev'),next=$('#'+flow+'Next');prev.style.visibility=n?'visible':'hidden';next.textContent=n<3?'下一步':flow==='clone'?'开始生成复刻视频':'开始生成口播视频';next.classList.toggle('hidden',state[flow].generated);if(flow==='avatar'&&n===3)updateChecks()}
function error(flow){const n=state[flow+'Step'];if(flow==='clone'){if(n===0&&!state.clone.reference)return'请上传参考视频';if(n===1&&!state.clone.analyzed)return'请完成参考视频分析';if(n===2&&!state.clone.subjects.length)return'请上传替换主体';if(n===3&&$('#cloneBrief').value.trim().length<8)return'请填写至少 8 个字的新视频内容'}else{if(n===0&&!state.avatar.media)return'请上传照片或自拍视频';if(n===1&&!state.avatar.voice)return'请上传录音或说话视频';if(n===2&&state.avatar.script.trim().length<8)return'请输入至少 8 个字的口播文案'}return''}
function next(flow){const e=error(flow);if(e)return toast('当前步骤未完成',e,flow==='avatar');if(state[flow+'Step']<3){state[flow+'Step']++;renderSteps(flow);renderStage(flow);scrollTo({top:0,behavior:'smooth'})}else generate(flow)}function prev(flow){state[flow+'Step']=Math.max(0,state[flow+'Step']-1);renderSteps(flow);renderStage(flow)}
function url(f){try{return URL.createObjectURL(f)}catch{return''}}function esc(v){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function clearZone(zone){$$(':scope > video,:scope > img',zone).forEach(el=>{try{URL.revokeObjectURL(el.src)}catch{};el.remove()})}
function preview(zone,copy,file){clearZone(zone);const m=document.createElement(file.type.startsWith('video/')?'video':'img');m.src=url(file);if(m.tagName==='VIDEO'){m.muted=true;m.controls=true;m.playsInline=true}zone.prepend(m);copy.innerHTML=`<i class="ph ph-check-circle"></i><b>${esc(file.name)}</b><span>已在当前浏览器加载</span>`}
function buildPendingProject(flow){const isClone=flow==='clone';const text=isClone?$('#cloneBrief').value.trim():state.avatar.script.trim();return normalizeProject({title:text.slice(0,22)||(isClone?'新建视频复刻项目':'新建 AI 口播项目'),mode:flow,time:'刚刚',img:isClone?'https://images.unsplash.com/photo-1536240478700-b869070f9279?auto=format&fit=crop&w=220&q=70':'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=220&q=70',brief:text,status:'已完成'})}
function generate(flow){const pre=flow;$('#'+pre+'Idle').classList.add('hidden');$('#'+pre+'Generating').classList.remove('hidden');$('#'+pre+'Actions').classList.add('hidden');const ring=$('#'+pre+'Ring'),text=$('#'+pre+'Percent'),caption=$('#'+pre+'Caption');let p=0;ring.style.setProperty('--p','0deg');text.textContent='0%';const timer=setInterval(()=>{p=Math.min(100,p+13);ring.style.setProperty('--p',p*3.6+'deg');text.textContent=p+'%';caption.textContent=p<30?'正在分析素材…':p<60?'正在生成画面与声音…':p<100?'正在合成与质检…':'生成完成';if(p===100){clearInterval(timer);setTimeout(()=>{$('#'+pre+'Generating').classList.add('hidden');$('#'+pre+'Result').classList.remove('hidden');state[flow].generated=true;state[flow].pendingProject=buildPendingProject(flow);renderStage(flow);ensureResultActions(flow);toast(flow==='clone'?'视频复刻流程完成':'AI 口播流程完成','结果尚未保存，点击“保存到项目”进入历史记录。',flow==='avatar')},350)}},550)}
function ensureResultActions(flow){const saveBtn=$('#'+flow+'Save');if(!saveBtn)return;let wrap=saveBtn.parentElement.querySelector('.result-actions');if(!wrap){wrap=document.createElement('div');wrap.className='result-actions';saveBtn.parentElement.insertBefore(wrap,saveBtn);wrap.append(saveBtn)}if(!$('#'+flow+'Again')){const again=document.createElement('button');again.id=flow+'Again';again.className='secondary';again.textContent='再做一个';again.onclick=()=>resetFlow(flow,true);wrap.append(again)}if(!$('#'+flow+'ViewProjects')){const view=document.createElement('button');view.id=flow+'ViewProjects';view.className='secondary';view.textContent='查看历史';view.onclick=()=>go('projects');wrap.append(view)}}
function saveProject(flow){const p=state[flow].pendingProject;if(!p)return toast('没有待保存结果','请先完成一次生成。',flow==='avatar');if(!state.projects.some(x=>x.id===p.id)){state.projects.unshift(p);save();renderRecent()}toast('项目已保存','现在可以在历史中查看、重做或删除。',flow==='avatar');go('projects')}
function updateChecks(){const a=!!state.avatar.media,v=!!state.avatar.voice,s=state.avatar.script.trim().length>=8;$('#mediaState').textContent=a?'已完成':'未完成';$('#voiceState').textContent=v?'已完成':'未完成';$('#scriptState').textContent=s?'已完成':'未完成'}
function bindProjectActions(root=document){$$('[data-project-view]',root).forEach(b=>b.onclick=()=>openProject(b.dataset.projectView));$$('[data-project-redo]',root).forEach(b=>b.onclick=()=>redoProject(b.dataset.projectRedo));$$('[data-project-delete]',root).forEach(b=>b.onclick=()=>confirmDelete(b))}
function renderRecent(){$('#recent').innerHTML=state.projects.slice(0,3).map(p=>`<button class="recent-card" data-project-view="${esc(p.id)}"><img src="${esc(p.img)}" alt=""><div><b>${esc(p.title)}</b><span>${esc(p.time)} · ${p.mode==='clone'?'视频复刻':'AI 口播'} · ${esc(p.status)}</span></div></button>`).join('');bindProjectActions($('#recent'))}
function ensureFilters(){let f=$('#projectFilters');if(f)return;f=document.createElement('div');f.id='projectFilters';f.className='history-filters';f.innerHTML='<button data-filter="all">全部</button><button data-filter="clone">视频复刻</button><button data-filter="avatar">AI 口播</button>';$('#projectList').before(f);$$('[data-filter]',f).forEach(b=>b.onclick=()=>{state.projectFilter=b.dataset.filter;renderProjects()})}
function renderProjects(){ensureFilters();$$('[data-filter]',$('#projectFilters')).forEach(b=>b.classList.toggle('on',b.dataset.filter===state.projectFilter));const rows=state.projects.filter(p=>state.projectFilter==='all'||p.mode===state.projectFilter);$('#projectList').innerHTML=rows.length?rows.map(p=>`<article data-project-card="${esc(p.id)}"><img src="${esc(p.img)}" alt=""><div><b>${esc(p.title)}</b><span>${esc(p.time)} · ${esc(p.status)} · ${esc(p.brief)}</span></div><em>${p.mode==='clone'?'视频复刻':'AI 口播'}</em><div class="project-actions"><button class="primary-mini" data-project-view="${esc(p.id)}">查看结果</button><button data-project-redo="${esc(p.id)}">再次创作</button><button data-project-delete="${esc(p.id)}">删除</button></div></article>`).join(''):'<div class="empty-history">这个分类还没有项目。</div>';bindProjectActions($('#projectList'))}
function ensureProjectModal(){let m=$('#projectModal');if(m)return m;m=document.createElement('div');m.id='projectModal';m.className='project-modal';m.innerHTML='<div class="project-dialog" role="dialog" aria-modal="true" aria-labelledby="projectModalTitle"><header><div><h3 id="projectModalTitle"></h3><p id="projectModalMeta"></p></div><button class="icon" id="projectModalClose" aria-label="关闭项目详情">×</button></header><div class="project-preview" id="projectModalPreview">▶</div><p id="projectModalBrief"></p><div class="project-actions"><button class="primary-mini" id="projectModalRedo">再次创作</button><button id="projectModalDelete">删除项目</button></div></div>';document.body.append(m);$('#projectModalClose').onclick=closeProjectModal;m.onclick=e=>{if(e.target===m)closeProjectModal()};return m}
function openProject(id){const p=state.projects.find(x=>x.id===id);if(!p)return toast('项目不存在','这条历史可能已经被删除。');const m=ensureProjectModal();$('#projectModalTitle').textContent=p.title;$('#projectModalMeta').textContent=`${p.mode==='clone'?'视频复刻':'AI 口播'} · ${p.time} · ${p.status}`;$('#projectModalBrief').textContent=p.brief||'模拟成片已保存。';$('#projectModalPreview').classList.toggle('avatar',p.mode==='avatar');$('#projectModalRedo').onclick=()=>{closeProjectModal();start(p.mode,{fresh:true})};const del=$('#projectModalDelete');del.textContent='删除项目';del.dataset.confirmed='';del.onclick=()=>confirmDelete(del,p.id);m.classList.add('show')}
function closeProjectModal(){$('#projectModal')?.classList.remove('show')}
function redoProject(id){const p=state.projects.find(x=>x.id===id);if(p)start(p.mode,{fresh:true})}
function confirmDelete(button,id=button.dataset.projectDelete){if(button.dataset.confirmed!=='yes'){button.dataset.confirmed='yes';button.textContent='确认删除';toast('再次点击确认删除','删除后无法恢复。');return}state.projects=state.projects.filter(p=>p.id!==id);save();renderProjects();renderRecent();closeProjectModal();toast('项目已删除','历史记录已更新。')}
function resetFlow(flow,navigate=false){if(flow==='clone'){state.cloneStep=0;state.clone={reference:null,analyzed:false,type:'person',subjects:[],generated:false,pendingProject:null};$('#refInput').value='';$('#subjectInput').value='';$('#cloneBrief').value='';clearZone($('#refZone'));$('#refCopy').innerHTML='<i class="ph ph-cloud-arrow-up"></i><b>点击选择参考视频</b><span>支持 MP4、MOV，建议 15–90 秒</span>';$('#analysis').innerHTML='<div><i class="ph ph-film-strip"></i><b>镜头结构</b><span>等待分析</span></div><div><i class="ph ph-wave-sine"></i><b>节奏结构</b><span>等待分析</span></div><div><i class="ph ph-text-aa"></i><b>字幕文案</b><span>等待分析</span></div><div><i class="ph ph-palette"></i><b>视觉风格</b><span>等待分析</span></div>';$('#analyze').disabled=false;$('#analyze').textContent='开始模拟分析';$('#subjectPreviews').innerHTML='';$('#subjectCopy').innerHTML='<i class="ph ph-user-focus"></i><b>上传人物照片或自拍视频</b><span>可多选，建议主体清晰完整</span>';$$('button',$('#replaceTabs')).forEach((b,i)=>b.classList.toggle('on',i===0))}else{state.avatarStep=0;state.avatar={media:null,kind:'photo',voice:null,source:'audio',script:'',generated:false,pendingProject:null};$('#avatarInput').value='';$('#voiceInput').value='';$('#script').value='';$('#count').textContent='0 / 2000';clearZone($('#avatarZone'));$('#avatarCopy').innerHTML='<i class="ph ph-identification-card"></i><b>上传一张正面照片</b><span>自然表情、光线均匀、五官无遮挡</span>';$('#voiceCopy').innerHTML='<i class="ph ph-waveform"></i><b>点击上传声音文件</b><span>真实上线后需要声音授权</span>';$$('button',$('#avatarTabs')).forEach((b,i)=>b.classList.toggle('on',i===0));$$('button',$('#voiceOptions')).forEach((b,i)=>b.classList.toggle('on',i===0));$('#avatarInput').accept='image/*';$('#voiceInput').accept='audio/*'}$('#'+flow+'Idle').classList.remove('hidden');$('#'+flow+'Generating').classList.add('hidden');$('#'+flow+'Result').classList.add('hidden');$('#'+flow+'Actions').classList.remove('hidden');$('#'+flow+'Next').classList.remove('hidden');renderSteps(flow);renderStage(flow);if(navigate)start(flow)}
function clearCloneSubjectsForType(type){if(state.clone.type===type)return;state.clone.type=type;state.clone.subjects=[];$('#subjectInput').value='';$('#subjectPreviews').innerHTML='';$('#subjectCopy').innerHTML=type==='person'?'<i class="ph ph-user-focus"></i><b>上传人物照片或自拍视频</b><span>可多选，建议主体清晰完整</span>':'<i class="ph ph-package"></i><b>上传产品图片或视频</b><span>建议多角度与干净背景</span>';renderSteps('clone');toast('替换类型已切换','请为新类型重新上传主体素材。')}
function clearAvatarMediaForKind(kind){if(state.avatar.kind===kind)return;state.avatar.kind=kind;state.avatar.media=null;$('#avatarInput').value='';clearZone($('#avatarZone'));$('#avatarInput').accept=kind==='photo'?'image/*':'video/*';$('#avatarCopy').innerHTML=kind==='photo'?'<i class="ph ph-identification-card"></i><b>上传一张正面照片</b><span>自然表情、光线均匀</span>':'<i class="ph ph-video-camera"></i><b>上传一段自拍视频</b><span>建议 10–30 秒正面说话</span>';renderSteps('avatar');toast('形象来源已切换','请重新上传匹配的形象素材。',true)}
function clearVoiceForSource(source){if(state.avatar.source===source)return;state.avatar.source=source;state.avatar.voice=null;$('#voiceInput').value='';$('#voiceInput').accept=source==='audio'?'audio/*':'video/*';$('#voiceCopy').innerHTML=source==='audio'?'<i class="ph ph-microphone"></i><b>点击上传录音文件</b><span>MP3、WAV，建议 30 秒以上</span>':'<i class="ph ph-video-camera"></i><b>上传已有说话视频</b><span>模拟从视频中提取声音</span>';renderSteps('avatar');toast('声音来源已切换','请重新上传匹配的声音素材。',true)}
function wireStaticControls(){$$('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));$$('[data-flow]').forEach(b=>b.onclick=()=>start(b.dataset.flow));$('#menu').onclick=openDrawer;$('#close').onclick=closeDrawer;$('#shade').onclick=closeDrawer;$('#clonePrev').onclick=()=>prev('clone');$('#cloneNext').onclick=()=>next('clone');$('#avatarPrev').onclick=()=>prev('avatar');$('#avatarNext').onclick=()=>next('avatar');const notification=$$('.top-actions .icon').find(b=>b.id!=='menu');if(notification){notification.classList.add('notice-dot');notification.setAttribute('aria-label','查看通知');notification.onclick=()=>{notification.classList.remove('notice-dot');toast('暂无新任务通知','生成任务和系统消息会显示在这里。')}}$$('.icon').forEach((b,i)=>{if(!b.getAttribute('aria-label'))b.setAttribute('aria-label',b.id==='menu'?'打开功能菜单':b.id==='close'?'关闭功能菜单':b.classList.contains('back')?'返回首页':`操作按钮 ${i+1}`)})}
wireStaticControls();
$('#refInput').onchange=e=>{const f=e.target.files[0];if(!f)return;state.clone.reference=f;state.clone.analyzed=false;preview($('#refZone'),$('#refCopy'),f);renderSteps('clone');toast('参考视频已选择','下一步会单独分析视频结构。')};
$('#analyze').onclick=()=>{if(!state.clone.reference)return toast('缺少参考视频','请返回第一步上传参考视频。');$('#analyze').disabled=true;$('#analyze').textContent='正在分析…';setTimeout(()=>{state.clone.analyzed=true;$('#analysis').innerHTML='<div><i class="ph ph-film-strip"></i><b>镜头结构</b><span>12 个镜头</span></div><div><i class="ph ph-wave-sine"></i><b>节奏结构</b><span>钩子＋演示＋CTA</span></div><div><i class="ph ph-text-aa"></i><b>字幕文案</b><span>关键词放大</span></div><div><i class="ph ph-palette"></i><b>视觉风格</b><span>明亮蓝紫调</span></div>';$('#analyze').disabled=false;$('#analyze').textContent='重新模拟分析';renderSteps('clone');toast('分析完成','已生成模拟 Video DNA。')},1100)};
$$('button',$('#replaceTabs')).forEach(b=>b.onclick=()=>{$$('button',$('#replaceTabs')).forEach(x=>x.classList.remove('on'));b.classList.add('on');clearCloneSubjectsForType(b.dataset.type)});
$('#subjectInput').onchange=e=>{state.clone.subjects=[...e.target.files];if(!state.clone.subjects.length)return;$('#subjectPreviews').innerHTML=state.clone.subjects.slice(0,4).map(f=>f.type.startsWith('video/')?`<video src="${url(f)}" muted></video>`:`<img src="${url(f)}">`).join('');$('#subjectCopy').innerHTML=`<i class="ph ph-check-circle"></i><b>已选择 ${state.clone.subjects.length} 个主体素材</b><span>${state.clone.type==='person'?'人物替换':'产品替换'}</span>`;renderSteps('clone');toast('替换主体已准备','参考视频和主体素材已经分开。')};
$$('button',$('#avatarTabs')).forEach(b=>b.onclick=()=>{$$('button',$('#avatarTabs')).forEach(x=>x.classList.remove('on'));b.classList.add('on');clearAvatarMediaForKind(b.dataset.kind)});
$('#avatarInput').onchange=e=>{const f=e.target.files[0];if(!f)return;state.avatar.media=f;preview($('#avatarZone'),$('#avatarCopy'),f);renderSteps('avatar');toast('数字分身素材已选择','下一步可以克隆声音。',true)};
$$('button',$('#voiceOptions')).forEach(b=>b.onclick=()=>{$$('button',$('#voiceOptions')).forEach(x=>x.classList.remove('on'));b.classList.add('on');clearVoiceForSource(b.dataset.source)});
$('#voiceInput').onchange=e=>{const f=e.target.files[0];if(!f)return;state.avatar.voice=f;$('#voiceCopy').innerHTML=`<i class="ph ph-check-circle"></i><b>${esc(f.name)}</b><span>${state.avatar.source==='audio'?'录音已加载':'已模拟提取音轨'}</span>`;renderSteps('avatar');toast('声音素材已准备','真实上线后需要声音授权。',true)};
$('#script').oninput=e=>{state.avatar.script=e.target.value;$('#count').textContent=e.target.value.length+' / 2000';renderSteps('avatar')};$$('.chips').forEach(g=>$$('button',g).forEach(b=>b.onclick=()=>{$$('button',g).forEach(x=>x.classList.remove('on'));b.classList.add('on')}));$('#cloneSave').onclick=()=>saveProject('clone');$('#avatarSave').onclick=()=>saveProject('avatar');document.addEventListener('keydown',e=>{if(e.key==='Escape'){closeDrawer();closeProjectModal()}});injectQACSS();renderRecent();renderProjects();save();renderSteps('clone');renderSteps('avatar');renderStage('clone');renderStage('avatar');toast('VideoClone OS V2 已启动','视频复刻与 AI 口播是两个独立功能。',true);
